### ISSUE TITLE
REST api for Hubs

### ISSUE THREAD

**Issue by latikak** [latikak/covey.town#3]
Implementation of the REST API for HUBs, unit tests and updating the town API.

**Comment by ChokchaiThanrukprasert** [comment]
### Work Breakdown for RESTful API

**Engineering Tasks**
1.	Design and implement an API operation that retrieves a list of hub identifications ~~and their portal location~~ in the user current map, which is used to enter other hubs when the user is outside a hub (roaming Covey.Town) ~~or to exit when the user is inside a hub~~.
2.	~~Design and implement an API operation that sends a request containing hub identification and password to the server to enter/change a hub. The request should return a response giving a map and information about the requested hub if the request succeeds while return a proper error message to prompt the user if the request fails.~~ No longer needed.
3.	~~Implement an API operation that sends a request to return to Covey.Town. The request should return the map of Covey.Town and the location for the user to be spawn.~~ No longer needed.

**Documentation Tasks**
1.	Write documentation on the purpose of the API operation that retrieve a list of hub identifications and their portal location in the user current map.
2.	Write an instruction on how to retrieve and handle the list of hub identifications and their portal location in the user current map.
3.	~~Write documentation on the purpose of the API operation that send a request to enter/change a hub.~~
4.	~~Write an instruction on how to send a request to enter/change a hub.~~
5.	~~Write documentation on the purpose of the API operation that send a request to return to Covey.Town.~~
6.	~~Write an instruction on how to send a request to return to Covey.Town.~~

**Infrastructure Tasks**
1.	Implement tests on the API operation that retrieves a list of hub identifications and their portal location in the user's current map. Verifies that the list is generated and returned as expected.
2.	~~Implement tests on the API operation that sends a request containing hub identification and password to the server to enter/change a hub. Verifies that the request returns the map and information/error message as expected.~~
3.	~~Implement tests on the API operation that sends a request to return to Covey.Town. Verifies that the request returns the Covey.Town map and correct user spawn location.~~
