### ISSUE TITLE
Socket API for Hubs

### ISSUE THREAD

**Issue by latikak** [latikak/covey.town#4]

**Comment by Archanajith** [comment]
**Engineering :** 
1.Define a  hubTownListener interface with the following methods-
       
       onPlayerJoined(newPlayer: Player): void;

       onPlayerMoved(movedPlayer: Player): void;

       onPlayerDisconnected(removedPlayer: Player): void;

2. Create **CoveyHubRequestHandler** -
      Create types **hubJoinRequest** 

       hubJoinHandler(requestData: HubJoinRequest);

       townSocketAdapter(socket: Socket);

       with the following two methods to be designed -
        onPlayerMoved(movedPlayer: Player) {},
       onPlayerDisconnected(removedPlayer: Player) {},

**Documentation:**
In addition to the existing requestHandlers and listeners , for the purpose of our project plan a new type must be defined while joining the hub . This will be named as hubJoinRequest . 

**Infrastructure:**
The following tests can be performed -
1. Dispatches movement updates to all clients in the same room
2. Informs all players when a player disconnects
3. Informs all new players when a player joins
